import type { NextPage } from 'next'
import Head from 'next/head'
import { FormEvent, FormEventHandler, useState } from 'react'
import SearchResults from '../Components/SearchResults'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [input, setInput] = useState('');
  const [results, setResults] = useState([]);
  
  async function handleSubmit(e: FormEvent){
      e.preventDefault();
      if(!input.trim()){
        return null; 
      }

      const response = await fetch(`http://localhost:3333/products?q=${input}`) 
      const data = await response.json();
      setResults(data);
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Performance with React - Conciliation </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <label>Search</label>
      <form onSubmit={handleSubmit}>
        <input type="text" value={input} onChange={(e) => setInput(e.target.value)}/>
        <button type='submit'>Buscar</button>
        </form>
        <SearchResults results={results}/>
    </div>
  )
}

export default Home
